events {}

http {
    upstream backend {
        server backend1.default.svc.cluster.local:80;
        server backend2.default.svc.cluster.local:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}